/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sem2_final;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class emp_insert extends javax.swing.JFrame {

    /**
     * Creates new form emp_insert
     */
    
    Connection con=null;
    PreparedStatement pst = null;
    
    public emp_insert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        RadioButton_male = new javax.swing.JRadioButton();
        RadioButton_female = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txt_mobiie = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_emp = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_empcode = new javax.swing.JTextField();
        txt_empname = new javax.swing.JTextField();
        btn_insert = new javax.swing.JButton();
        btn_process = new javax.swing.JButton();
        btn_ruf = new javax.swing.JButton();
        btn_emp = new javax.swing.JButton();
        btn_ruf1 = new javax.swing.JButton();
        btn_ruf3 = new javax.swing.JButton();
        btn_ruf4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DIAMOND MANAGEMENT SYSTEM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee Insert");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setText("Gender:");
        jLabel4.setName("lbl_gender"); // NOI18N

        RadioButton_male.setBackground(new java.awt.Color(204, 204, 255));
        RadioButton_male.setText("Male");
        RadioButton_male.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RadioButton_male.setName(""); // NOI18N
        RadioButton_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_maleActionPerformed(evt);
            }
        });

        RadioButton_female.setBackground(new java.awt.Color(204, 204, 255));
        RadioButton_female.setText("Female");
        RadioButton_female.setName(""); // NOI18N

        jLabel5.setText("Mobile Number:");
        jLabel5.setName("lbl_mobilenumber"); // NOI18N

        txt_mobiie.setBackground(new java.awt.Color(204, 204, 255));
        txt_mobiie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_mobiie.setName("txt_mobilenumber"); // NOI18N

        table_emp.setBackground(new java.awt.Color(204, 204, 255));
        table_emp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        table_emp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "emp_code", "emp_name", "gender", "mobile_number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_emp.setName("tbl_empdetails"); // NOI18N
        jScrollPane1.setViewportView(table_emp);

        jLabel3.setText("Employee Code:");
        jLabel3.setName("lbl_empcode"); // NOI18N

        jLabel6.setText("Employee Name:");
        jLabel6.setName("lbl_empname"); // NOI18N

        txt_empcode.setBackground(new java.awt.Color(204, 204, 255));
        txt_empcode.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_empcode.setName("txt_empcode"); // NOI18N
        txt_empcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_empcodeActionPerformed(evt);
            }
        });

        txt_empname.setBackground(new java.awt.Color(204, 204, 255));
        txt_empname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_empname.setName("txt_empname"); // NOI18N

        btn_insert.setBackground(new java.awt.Color(204, 204, 255));
        btn_insert.setText("Insert");
        btn_insert.setBorder(new javax.swing.border.MatteBorder(null));
        btn_insert.setName("btn_empinsert"); // NOI18N
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });

        btn_process.setText("Process");
        btn_process.setName("btn_addpcktinsert"); // NOI18N
        btn_process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_processActionPerformed(evt);
            }
        });

        btn_ruf.setText("Ruf");
        btn_ruf.setName("btn_addpcktinsert"); // NOI18N
        btn_ruf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rufActionPerformed(evt);
            }
        });

        btn_emp.setText("Packet");
        btn_emp.setName("btn_addpcktinsert"); // NOI18N
        btn_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empActionPerformed(evt);
            }
        });

        btn_ruf1.setText("Issue");
        btn_ruf1.setName("btn_addpcktinsert"); // NOI18N
        btn_ruf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ruf1ActionPerformed(evt);
            }
        });

        btn_ruf3.setText("Receive");
        btn_ruf3.setName("btn_addpcktinsert"); // NOI18N
        btn_ruf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ruf3ActionPerformed(evt);
            }
        });

        btn_ruf4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_ruf4.setText("Logout");
        btn_ruf4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_ruf4.setName("btn_addpcktinsert"); // NOI18N
        btn_ruf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ruf4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_empcode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_empname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(RadioButton_male)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioButton_female, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_ruf, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_mobiie, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_ruf1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(btn_ruf4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btn_process, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(btn_ruf3)
                .addGap(164, 164, 164))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txt_empcode, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txt_empname, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(RadioButton_male)
                            .addComponent(RadioButton_female))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_mobiie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ruf3)
                    .addComponent(btn_emp)
                    .addComponent(btn_process))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ruf4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ruf1)
                    .addComponent(btn_ruf))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RadioButton_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton_maleActionPerformed

    private void txt_empcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_empcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_empcodeActionPerformed

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        // TODO add your handling code here:
        try{
            String gender = "";
            Class.forName("com.mysql.jdbc.Driver");
            String query ="INSERT INTO `employee`( `emp_code`,`emp_name`, `gender`, `mobile_number`) VALUES (?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/diamond_packager","root","");
            pst=con.prepareStatement(query);
            pst.setString(4,txt_mobiie.getText());
            pst.setString(2,txt_empname.getText());
            if(RadioButton_male.isSelected()) {
                gender="Male";}
            else{
                gender="Female";}
            pst.setString(3, gender);
            pst.setString(1,txt_empcode.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"EMPLOYEE DETAILS INSERTED SUCCESSFULLY");

            Statement st = con.createStatement();
            String sql = "SELECT * FROM employee";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {

                String emp_code = String.valueOf(rs.getInt("emp_code"));
                String emp_name = rs.getString("emp_name");
                gender = rs.getString("gender");
                String mobile_number = String.valueOf(rs.getLong("mobile_number"));

                String tbData[] = {emp_code, emp_name, gender, mobile_number};
                DefaultTableModel tblModel = (DefaultTableModel)table_emp.getModel();
                tblModel.setRowCount(0);
                tblModel.addRow(tbData);
                //               JOptionPane.showMessageDialog(null, tblModel);
                //               tblModel.addRow(tbData);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btn_insertActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
                try{
           Class.forName("com.mysql.jdbc.Driver");
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/diamond_packager","root","");
           Statement st = con.createStatement();
           String sql = "SELECT * FROM employee";
           ResultSet rs = st.executeQuery(sql);
           int c=0;
           while(rs.next())
           {
               
               String emp_code = String.valueOf(rs.getInt("emp_code"));
               String emp_name = rs.getString("emp_name");
               String gender = rs.getString("gender");
               String mobile_number = String.valueOf(rs.getLong("mobile_number"));
               
               String tbData[] = {emp_code, emp_name, gender, mobile_number};
               DefaultTableModel tblModel = (DefaultTableModel)table_emp.getModel();
               tblModel.setRowCount(c++);
               tblModel.addRow(tbData);
//               JOptionPane.showMessageDialog(null, tblModel);
//               tblModel.addRow(tbData);
               
           }
       } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btn_processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_processActionPerformed
        // TODO add your handling code here:
        new Process_insert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_processActionPerformed

    private void btn_rufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rufActionPerformed
        // TODO add your handling code here:
        new ruf_insert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_rufActionPerformed

    private void btn_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empActionPerformed
        // TODO add your handling code here:
        new Packet_insert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_empActionPerformed

    private void btn_ruf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ruf1ActionPerformed
        // TODO add your handling code here:
        new IssueInsert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ruf1ActionPerformed

    private void btn_ruf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ruf3ActionPerformed
        // TODO add your handling code here:
        new ReceiveInsert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ruf3ActionPerformed

    private void btn_ruf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ruf4ActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ruf4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emp_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emp_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emp_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emp_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emp_insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioButton_female;
    private javax.swing.JRadioButton RadioButton_male;
    private javax.swing.JButton btn_emp;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_process;
    private javax.swing.JButton btn_ruf;
    private javax.swing.JButton btn_ruf1;
    private javax.swing.JButton btn_ruf3;
    private javax.swing.JButton btn_ruf4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_emp;
    private javax.swing.JTextField txt_empcode;
    private javax.swing.JTextField txt_empname;
    private javax.swing.JTextField txt_mobiie;
    // End of variables declaration//GEN-END:variables
}
