/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sem2_final;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class IssueInsert extends javax.swing.JFrame {

    /**
     * Creates new form IssueInsert
     */
    
    Connection con=null;
    PreparedStatement pst = null;
    
    public IssueInsert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_issue = new javax.swing.JButton();
        cmb_rufname = new javax.swing.JComboBox<>();
        lbl_leftweight = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmb_packetno = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmb_process = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmb_emp = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        lbl_empname = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_process = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_packetweight = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_issue = new javax.swing.JTable();
        btn_process = new javax.swing.JButton();
        btn_ruf = new javax.swing.JButton();
        btn_emp = new javax.swing.JButton();
        btn_ruf1 = new javax.swing.JButton();
        btn_ruf3 = new javax.swing.JButton();
        btn_ruf4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DIAMOND MANAGEMENT SYSTEM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Issue Packet");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Process Name:");
        jLabel9.setName("lbl_processnameissueinsert"); // NOI18N

        btn_issue.setBackground(new java.awt.Color(204, 204, 255));
        btn_issue.setText("Insert");
        btn_issue.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_issue.setName("btn_insertissueinsert"); // NOI18N
        btn_issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_issueActionPerformed(evt);
            }
        });

        cmb_rufname.setBackground(new java.awt.Color(204, 204, 255));
        cmb_rufname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Ruf_name" }));
        cmb_rufname.setToolTipText("");
        cmb_rufname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmb_rufname.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_rufnameItemStateChanged(evt);
            }
        });
        cmb_rufname.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cmb_rufnameInputMethodTextChanged(evt);
            }
        });
        cmb_rufname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_rufnameActionPerformed(evt);
            }
        });
        cmb_rufname.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmb_rufnamePropertyChange(evt);
            }
        });
        cmb_rufname.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                cmb_rufnameVetoableChange(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ruf Name:");
        jLabel3.setName("lbl_rufnameissueinsert"); // NOI18N

        cmb_packetno.setBackground(new java.awt.Color(204, 204, 255));
        cmb_packetno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Packet No." }));
        cmb_packetno.setToolTipText("");
        cmb_packetno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmb_packetno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_packetnoItemStateChanged(evt);
            }
        });
        cmb_packetno.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cmb_packetnoInputMethodTextChanged(evt);
            }
        });
        cmb_packetno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_packetnoActionPerformed(evt);
            }
        });
        cmb_packetno.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmb_packetnoPropertyChange(evt);
            }
        });
        cmb_packetno.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                cmb_packetnoVetoableChange(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Weight: ");
        jLabel4.setName("lbl_weightrufnameissueinser"); // NOI18N

        cmb_process.setBackground(new java.awt.Color(204, 204, 255));
        cmb_process.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Process" }));
        cmb_process.setToolTipText("");
        cmb_process.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmb_process.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_processItemStateChanged(evt);
            }
        });
        cmb_process.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cmb_processInputMethodTextChanged(evt);
            }
        });
        cmb_process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_processActionPerformed(evt);
            }
        });
        cmb_process.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmb_processPropertyChange(evt);
            }
        });
        cmb_process.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                cmb_processVetoableChange(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Packet No: ");
        jLabel5.setName("lbl_pcktnoissueinsert"); // NOI18N

        cmb_emp.setBackground(new java.awt.Color(204, 204, 255));
        cmb_emp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Emp" }));
        cmb_emp.setToolTipText("");
        cmb_emp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmb_emp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_empItemStateChanged(evt);
            }
        });
        cmb_emp.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cmb_empInputMethodTextChanged(evt);
            }
        });
        cmb_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_empActionPerformed(evt);
            }
        });
        cmb_emp.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmb_empPropertyChange(evt);
            }
        });
        cmb_emp.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                cmb_empVetoableChange(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Weight: ");
        jLabel6.setName("lbl_weightpcktnoissueinsert"); // NOI18N

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Emp Code: ");
        jLabel7.setName("lbl_empcodeissueinsert"); // NOI18N

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Emp. Name:");
        jLabel8.setName("lbl_empnameissueinsert"); // NOI18N

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Process Code:");
        jLabel10.setName("lbl_processcodeissueinsert"); // NOI18N

        tbl_issue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ruf_name", "packet_no", "emp_code", "process_code"
            }
        ));
        jScrollPane1.setViewportView(tbl_issue);

        btn_process.setText("Process");
        btn_process.setName("btn_addpcktinsert"); // NOI18N
        btn_process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_processActionPerformed(evt);
            }
        });

        btn_ruf.setText("Ruf");
        btn_ruf.setName("btn_addpcktinsert"); // NOI18N
        btn_ruf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rufActionPerformed(evt);
            }
        });

        btn_emp.setText("Emp");
        btn_emp.setName("btn_addpcktinsert"); // NOI18N
        btn_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empActionPerformed(evt);
            }
        });

        btn_ruf1.setText("Packet");
        btn_ruf1.setName("btn_addpcktinsert"); // NOI18N
        btn_ruf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ruf1ActionPerformed(evt);
            }
        });

        btn_ruf3.setText("Receive");
        btn_ruf3.setName("btn_addpcktinsert"); // NOI18N
        btn_ruf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ruf3ActionPerformed(evt);
            }
        });

        btn_ruf4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_ruf4.setText("Logout");
        btn_ruf4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_ruf4.setName("btn_addpcktinsert"); // NOI18N
        btn_ruf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ruf4ActionPerformed(evt);
            }
        });

        jLabel11.setText("Issues Packets:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmb_rufname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_leftweight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmb_packetno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb_emp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmb_process, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_empname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_process, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_packetweight, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_issue, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_process, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ruf, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_ruf3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_ruf4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_ruf1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cmb_rufname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(13, 13, 13)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(cmb_packetno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbl_leftweight))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lbl_packetweight))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmb_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(lbl_empname, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmb_process, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(lbl_process, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_issue, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_emp)
                            .addComponent(btn_ruf1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ruf3)
                            .addComponent(btn_ruf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_process)
                            .addComponent(btn_ruf4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_issueActionPerformed
        // TODO add your handling code here:
        try{

            int ruf_code = cmb_rufname.getSelectedIndex();
            String packet_no = (String)cmb_packetno.getSelectedItem();
            String emp_no = (String)cmb_emp.getSelectedItem();
            String process_no = (String)cmb_process.getSelectedItem();
            Class.forName("com.mysql.jdbc.Driver");
            String query ="INSERT INTO `issue`( `emp_code`,`packet_no`, `process_code`, `ruf_id`, `status`) VALUES (?,?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/diamond_packager","root","");
            pst=con.prepareStatement(query);
            pst.setString(1,emp_no);
            pst.setString(2,packet_no);
            pst.setString(3,process_no);
            pst.setString(4,Integer.toString(ruf_code));
            pst.setString(5,"true");
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Packet Issued");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btn_issueActionPerformed

    private void cmb_rufnameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_rufnameItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_rufnameItemStateChanged

    private void cmb_rufnameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cmb_rufnameInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_rufnameInputMethodTextChanged

    private void cmb_rufnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_rufnameActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/diamond_packager","root","");
            Statement st = con.createStatement();
            String ruf_name=(String) cmb_rufname.getSelectedItem();
            String sql = "SELECT weight FROM ruf WHERE ruf_name= '"+ruf_name+"'";
            ResultSet rs = st.executeQuery(sql);
            rs.next();

            Statement st1 = con.createStatement();
            String sql1 = "SELECT IFNULL(SUM(packet_weight), 0) as sum_weight from packet p where ruf_id = (select ruf_id from ruf where ruf_name='"+ruf_name+"')";
            ResultSet rs1 = st1.executeQuery(sql1);
            rs1.next();
            float left_weight = Float.parseFloat(rs.getString(1)) - Float.parseFloat(rs1.getString(1));
            lbl_leftweight.setText(String.valueOf(left_weight));

            Statement st2 = con.createStatement();
            String sql2 = "SELECT packet_no FROM packet p, ruf r WHERE p.ruf_id = r.ruf_id and r.ruf_name= '"+ruf_name+"'";
            ResultSet rs2 = st2.executeQuery(sql2);

            int itemCount = cmb_packetno.getItemCount();
            while(itemCount > 1){
                cmb_packetno.removeItemAt(itemCount-1);
                itemCount--;
            }
            while(rs2.next())
            {
                String p_no = rs2.getString(1);
                cmb_packetno.addItem(p_no);
            }
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_cmb_rufnameActionPerformed

    private void cmb_rufnamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmb_rufnamePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_rufnamePropertyChange

    private void cmb_rufnameVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_cmb_rufnameVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_rufnameVetoableChange

    private void cmb_packetnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_packetnoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_packetnoItemStateChanged

    private void cmb_packetnoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cmb_packetnoInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_packetnoInputMethodTextChanged

    private void cmb_packetnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_packetnoActionPerformed
        // TODO add your handling code here:
        try{
            String ruf_name=(String) cmb_rufname.getSelectedItem();
            String packet_no = (String)cmb_packetno.getSelectedItem();
            Statement st = con.createStatement();
            String sql = "SELECT packet_weight FROM packet p, ruf r WHERE p.ruf_id = r.ruf_id and r.ruf_name= '"+ruf_name+"' and p.packet_no ="+packet_no+" ";
            ResultSet rs = st.executeQuery(sql);
            rs.next();
            lbl_packetweight.setText(rs.getString(1));
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_cmb_packetnoActionPerformed

    private void cmb_packetnoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmb_packetnoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_packetnoPropertyChange

    private void cmb_packetnoVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_cmb_packetnoVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_packetnoVetoableChange

    private void cmb_processItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_processItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_processItemStateChanged

    private void cmb_processInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cmb_processInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_processInputMethodTextChanged

    private void cmb_processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_processActionPerformed
        // TODO add your handling code here:
        try{
            String process_code = (String)cmb_process.getSelectedItem();
            Statement st = con.createStatement();
            String sql = "SELECT process_name from process where process_code = "+process_code+"";
            ResultSet rs = st.executeQuery(sql);
            rs.next();
            lbl_process.setText(rs.getString(1));
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_cmb_processActionPerformed

    private void cmb_processPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmb_processPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_processPropertyChange

    private void cmb_processVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_cmb_processVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_processVetoableChange

    private void cmb_empItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_empItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_empItemStateChanged

    private void cmb_empInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cmb_empInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_empInputMethodTextChanged

    private void cmb_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_empActionPerformed
        // TODO add your handling code here:
        try{
            String emp_code = (String)cmb_emp.getSelectedItem();
            Statement st = con.createStatement();
            String sql = "SELECT emp_name from employee where emp_code = "+emp_code+"";
            ResultSet rs = st.executeQuery(sql);
            rs.next();
            lbl_empname.setText(rs.getString("emp_name"));
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_cmb_empActionPerformed

    private void cmb_empPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmb_empPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_empPropertyChange

    private void cmb_empVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_cmb_empVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_empVetoableChange

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
           try{
           Class.forName("com.mysql.jdbc.Driver");
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/diamond_packager","root","");
           Statement st = con.createStatement();
           String sql = "SELECT ruf_name FROM ruf";
           ResultSet rs = st.executeQuery(sql);
//           int c=0;
           while(rs.next())
           {        
               String ruf_name = rs.getString("ruf_name");
               cmb_rufname.addItem(ruf_name);               
           }
           
           
           Statement st1 = con.createStatement();
           String sql1 = "SELECT emp_code FROM employee";
           ResultSet rs1 = st1.executeQuery(sql1);
           while(rs1.next())
           {
               cmb_emp.addItem(rs1.getString(1));
           }
           
           Statement st2 = con.createStatement();
           String sql2 = "SELECT process_code FROM process";
           ResultSet rs2 = st2.executeQuery(sql2);
           while(rs2.next())
           {
               cmb_process.addItem(rs2.getString(1));
               
           }
           
           Statement st3 = con.createStatement();
           String sql3 = "SELECT r.ruf_name, i.packet_no, i.emp_code, i.process_code FROM ruf r, issue i where r.ruf_id = i.ruf_id";
           ResultSet rs3 = st.executeQuery(sql3);
           int c=0;
           while(rs3.next())
           {
             String ruf_name =rs3.getString(1);
             String packet_no = rs3.getString(2);
             String emp_code = rs3.getString(3);
             String process_code = String.valueOf(rs3.getFloat(4));
               
             String tbData[] = {ruf_name, packet_no, emp_code, process_code};
             DefaultTableModel tblModel = (DefaultTableModel)tbl_issue.getModel();
               tblModel.setRowCount(c++);
               tblModel.addRow(tbData);
           }
       } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btn_processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_processActionPerformed
        // TODO add your handling code here:
        new Process_insert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_processActionPerformed

    private void btn_rufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rufActionPerformed
        // TODO add your handling code here:
        new ruf_insert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_rufActionPerformed

    private void btn_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empActionPerformed
        // TODO add your handling code here:
        new emp_insert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_empActionPerformed

    private void btn_ruf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ruf1ActionPerformed
        // TODO add your handling code here:
        new Packet_insert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ruf1ActionPerformed

    private void btn_ruf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ruf3ActionPerformed
        // TODO add your handling code here:
        new ReceiveInsert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ruf3ActionPerformed

    private void btn_ruf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ruf4ActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ruf4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueInsert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_emp;
    private javax.swing.JButton btn_issue;
    private javax.swing.JButton btn_process;
    private javax.swing.JButton btn_ruf;
    private javax.swing.JButton btn_ruf1;
    private javax.swing.JButton btn_ruf3;
    private javax.swing.JButton btn_ruf4;
    private javax.swing.JComboBox<String> cmb_emp;
    private javax.swing.JComboBox<String> cmb_packetno;
    private javax.swing.JComboBox<String> cmb_process;
    private javax.swing.JComboBox<String> cmb_rufname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_empname;
    private javax.swing.JLabel lbl_leftweight;
    private javax.swing.JLabel lbl_packetweight;
    private javax.swing.JLabel lbl_process;
    private javax.swing.JTable tbl_issue;
    // End of variables declaration//GEN-END:variables
}
