/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sem2_final;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class Packet_insert extends javax.swing.JFrame {

    /**
     * Creates new form Packet_insert
     */
    Connection con=null;
    PreparedStatement pst = null;
    public Packet_insert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ruf2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_rufnamepcktinsrt = new javax.swing.JLabel();
        cmb_rufnamepcktinsrt = new javax.swing.JComboBox<>();
        lbl_pcktnopcktinsrt = new javax.swing.JLabel();
        lbl_pcktweightpcktinsrt = new javax.swing.JLabel();
        lbl_leftweightpcktinsrt = new javax.swing.JLabel();
        txt_pcktweightpcktinsrt = new javax.swing.JTextField();
        txt_pcktno = new javax.swing.JTextField();
        lblauto_leftweightpcktinsert = new javax.swing.JLabel();
        btn_addpcktinsrt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pcktinsrt = new javax.swing.JTable();
        btn_emp = new javax.swing.JButton();
        btn_process = new javax.swing.JButton();
        btn_ruf = new javax.swing.JButton();
        btn_ruf1 = new javax.swing.JButton();
        btn_ruf3 = new javax.swing.JButton();
        btn_ruf4 = new javax.swing.JButton();

        btn_ruf2.setText("Issue");
        btn_ruf2.setName("btn_addpcktinsert"); // NOI18N
        btn_ruf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ruf2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DIAMOND MANAGEMENT SYSTEM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Packet Insert");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        lbl_rufnamepcktinsrt.setText("Ruf Name:");
        lbl_rufnamepcktinsrt.setName("lbl_rufname"); // NOI18N

        cmb_rufnamepcktinsrt.setBackground(new java.awt.Color(204, 204, 255));
        cmb_rufnamepcktinsrt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Ruf_name" }));
        cmb_rufnamepcktinsrt.setToolTipText("");
        cmb_rufnamepcktinsrt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_rufnamepcktinsrtItemStateChanged(evt);
            }
        });
        cmb_rufnamepcktinsrt.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cmb_rufnamepcktinsrtInputMethodTextChanged(evt);
            }
        });
        cmb_rufnamepcktinsrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_rufnamepcktinsrtActionPerformed(evt);
            }
        });
        cmb_rufnamepcktinsrt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmb_rufnamepcktinsrtPropertyChange(evt);
            }
        });
        cmb_rufnamepcktinsrt.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                cmb_rufnamepcktinsrtVetoableChange(evt);
            }
        });

        lbl_pcktnopcktinsrt.setText("Packet No.:");
        lbl_pcktnopcktinsrt.setName("lbl_pcktno"); // NOI18N

        lbl_pcktweightpcktinsrt.setText("Packet Weight :");
        lbl_pcktweightpcktinsrt.setName("lbl_pcktweight"); // NOI18N

        lbl_leftweightpcktinsrt.setText("Left Weight:");
        lbl_leftweightpcktinsrt.setName("lbl_rufleftweight"); // NOI18N

        txt_pcktweightpcktinsrt.setBackground(new java.awt.Color(204, 204, 255));
        txt_pcktweightpcktinsrt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_pcktweightpcktinsrt.setName("txt_pcktweightpcktinsert"); // NOI18N
        txt_pcktweightpcktinsrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pcktweightpcktinsrtActionPerformed(evt);
            }
        });

        txt_pcktno.setBackground(new java.awt.Color(204, 204, 255));
        txt_pcktno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_pcktno.setName("txt_pcktnopcktinsert"); // NOI18N

        lblauto_leftweightpcktinsert.setText("l");

        btn_addpcktinsrt.setText("ADD");
        btn_addpcktinsrt.setName("btn_addpcktinsert"); // NOI18N
        btn_addpcktinsrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addpcktinsrtActionPerformed(evt);
            }
        });

        tbl_pcktinsrt.setBackground(new java.awt.Color(204, 204, 255));
        tbl_pcktinsrt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl_pcktinsrt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ruf name", "packet no", "packet weight"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_pcktinsrt.setName("tbl_pcktinsert"); // NOI18N
        jScrollPane1.setViewportView(tbl_pcktinsrt);

        btn_emp.setText("Emp");
        btn_emp.setName("btn_addpcktinsert"); // NOI18N
        btn_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empActionPerformed(evt);
            }
        });

        btn_process.setText("Process");
        btn_process.setName("btn_addpcktinsert"); // NOI18N
        btn_process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_processActionPerformed(evt);
            }
        });

        btn_ruf.setText("Ruf");
        btn_ruf.setName("btn_addpcktinsert"); // NOI18N
        btn_ruf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rufActionPerformed(evt);
            }
        });

        btn_ruf1.setText("Issue");
        btn_ruf1.setName("btn_addpcktinsert"); // NOI18N
        btn_ruf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ruf1ActionPerformed(evt);
            }
        });

        btn_ruf3.setText("Receive");
        btn_ruf3.setName("btn_addpcktinsert"); // NOI18N
        btn_ruf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ruf3ActionPerformed(evt);
            }
        });

        btn_ruf4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_ruf4.setText("Logout");
        btn_ruf4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_ruf4.setName("btn_addpcktinsert"); // NOI18N
        btn_ruf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ruf4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_pcktnopcktinsrt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_pcktno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_rufnamepcktinsrt)
                            .addComponent(lbl_leftweightpcktinsrt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblauto_leftweightpcktinsert, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_rufnamepcktinsrt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_pcktweightpcktinsrt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_addpcktinsrt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_pcktweightpcktinsrt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_ruf, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(btn_ruf3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btn_ruf1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(btn_ruf4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addComponent(btn_process, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(532, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_rufnamepcktinsrt)
                            .addComponent(cmb_rufnamepcktinsrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_leftweightpcktinsrt)
                            .addComponent(lblauto_leftweightpcktinsert))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_pcktnopcktinsrt)
                            .addComponent(txt_pcktno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_pcktweightpcktinsrt)
                            .addComponent(txt_pcktweightpcktinsrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_addpcktinsrt)
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ruf)
                    .addComponent(btn_ruf3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_emp)
                    .addComponent(btn_ruf1)
                    .addComponent(btn_ruf4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(263, Short.MAX_VALUE)
                    .addComponent(btn_process)
                    .addGap(134, 134, 134)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_rufnamepcktinsrtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_rufnamepcktinsrtItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cmb_rufnamepcktinsrtItemStateChanged

    private void cmb_rufnamepcktinsrtInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cmb_rufnamepcktinsrtInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cmb_rufnamepcktinsrtInputMethodTextChanged

    private void cmb_rufnamepcktinsrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_rufnamepcktinsrtActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/diamond_packager","root","");
            Statement st = con.createStatement();
            String ruf_name=(String) cmb_rufnamepcktinsrt.getSelectedItem();
            String sql = "SELECT weight FROM ruf WHERE ruf_name= '"+ruf_name+"'";
            ResultSet rs = st.executeQuery(sql);
            rs.next();

            Statement st1 = con.createStatement();
            String sql1 = "SELECT IFNULL(SUM(packet_weight),0) as sum_weight from packet p where ruf_id = (SELECT ruf_id FROM ruf WHERE ruf_name= '"+ruf_name+"')";
            ResultSet rs1 = st1.executeQuery(sql1);
            rs1.next();
            float left_weight = Float.parseFloat(rs.getString(1)) - Float.parseFloat(rs1.getString(1));
            lblauto_leftweightpcktinsert.setText(String.valueOf(left_weight));
            
            
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_cmb_rufnamepcktinsrtActionPerformed

    private void cmb_rufnamepcktinsrtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmb_rufnamepcktinsrtPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_cmb_rufnamepcktinsrtPropertyChange

    private void cmb_rufnamepcktinsrtVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_cmb_rufnamepcktinsrtVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_rufnamepcktinsrtVetoableChange

    private void txt_pcktweightpcktinsrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pcktweightpcktinsrtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pcktweightpcktinsrtActionPerformed

    private void btn_addpcktinsrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addpcktinsrtActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String query ="INSERT INTO `packet`(`ruf_id`, `packet_no`, `packet_weight`) VALUES (?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/diamond_packager","root","");
            pst=con.prepareStatement(query);
            pst.setString(2,txt_pcktno.getText());
            pst.setString(3,txt_pcktweightpcktinsrt.getText());

            Statement st1 = con.createStatement();
            String ruf_name=(String) cmb_rufnamepcktinsrt.getSelectedItem();
            String sql = "SELECT ruf_id FROM ruf WHERE ruf_name= '"+ruf_name+"'";
            ResultSet rs = st1.executeQuery(sql);
            rs.next();

            pst.setString(1,rs.getString(1));

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Packet inserted");

            Statement st2 = con.createStatement();
            String sql1 = "SELECT weight FROM ruf WHERE ruf_name= '"+ruf_name+"'";
            ResultSet rs1 = st2.executeQuery(sql1);
            rs1.next();

            Statement st3 = con.createStatement();
            String sql2 = "SELECT SUM(packet_weight) as sum_weight from packet p where ruf_id = (select ruf_id from ruf where ruf_name='"+ruf_name+"')";
            ResultSet rs2 = st3.executeQuery(sql2);
            rs2.next();
            float left_weight1 = Float.parseFloat(rs1.getString(1)) - Float.parseFloat(rs2.getString(1));
            lblauto_leftweightpcktinsert.setText(String.valueOf(left_weight1));

            //           Statement st = con.createStatement();
            //           String sql = "SELECT * FROM employee";
            //           ResultSet rs = st.executeQuery(sql);
            //           int c=0;
            //           while(rs.next())
            //           {
                //
                //               String emp_code = String.valueOf(rs.getInt("emp_code"));
                //               String emp_name = rs.getString("emp_name");
                //               gender = rs.getString("gender");
                //               String mobile_number = String.valueOf(rs.getLong("mobile_number"));
                //
                //               String tbData[] = {emp_code, emp_name, gender, mobile_number};
                //               DefaultTableModel tblModel = (DefaultTableModel)table_emp.getModel();
                //               tblModel.setRowCount(c++);
                //               tblModel.addRow(tbData);
                ////               JOptionPane.showMessageDialog(null, tblModel);
                ////               tblModel.addRow(tbData);
                //
                //           }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btn_addpcktinsrtActionPerformed

    private void btn_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empActionPerformed
        // TODO add your handling code here:
        new emp_insert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_empActionPerformed

    private void btn_processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_processActionPerformed
        // TODO add your handling code here:
        new Process_insert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_processActionPerformed

    private void btn_rufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rufActionPerformed
        // TODO add your handling code here:
        new ruf_insert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_rufActionPerformed

    private void btn_ruf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ruf1ActionPerformed
        // TODO add your handling code here:
        new IssueInsert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ruf1ActionPerformed

    private void btn_ruf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ruf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ruf2ActionPerformed

    private void btn_ruf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ruf3ActionPerformed
        // TODO add your handling code here:
        new ReceiveInsert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ruf3ActionPerformed

    private void btn_ruf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ruf4ActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ruf4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
           Class.forName("com.mysql.jdbc.Driver");
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/diamond_packager","root","");
           Statement st = con.createStatement();
           String sql = "SELECT ruf_name FROM ruf";
           ResultSet rs = st.executeQuery(sql);
           int c=0;
//           cmb_rufnamepcktinsrt.removeAllItems();
//           cmb_rufnamepcktinsrt.addItem("");
           while(rs.next())
          {
                        
               String ruf_name = rs.getString("ruf_name");
               cmb_rufnamepcktinsrt.addItem(ruf_name);
//               String emp_name = rs.getString("emp_name");
//               String gender = rs.getString("gender");
//               String mobile_number = String.valueOf(rs.getLong("mobile_number"));
//               
               
//               DefaultTableModel tblModel = (DefaultTableModel)table_emp.getModel();
//               tblModel.setRowCount(c++);
//               tblModel.addRow(tbData);
//               JOptionPane.showMessageDialog(null, tblModel);
//               tblModel.addRow(tbData);
            Statement st1 = con.createStatement();
            String sql1 = "SELECT ruf_name, packet_no, packet_weight FROM packet p, ruf r where r.ruf_id = p.ruf_id";
            ResultSet rs1 = st1.executeQuery(sql1);
            int s=0;
            while(rs1.next())
            {
                String ruf_name1 = rs1.getString(1);
                String packet_no = String.valueOf(rs1.getInt(2));
                String packet_weight = String.valueOf(rs1.getInt(3));

                String tbData[] = {ruf_name1, packet_no, packet_weight};
                DefaultTableModel tblModel = (DefaultTableModel)tbl_pcktinsrt.getModel();
                tblModel.setRowCount(s++);
                tblModel.addRow(tbData);
            }
           }
       } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Packet_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Packet_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Packet_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Packet_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Packet_insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addpcktinsrt;
    private javax.swing.JButton btn_emp;
    private javax.swing.JButton btn_process;
    private javax.swing.JButton btn_ruf;
    private javax.swing.JButton btn_ruf1;
    private javax.swing.JButton btn_ruf2;
    private javax.swing.JButton btn_ruf3;
    private javax.swing.JButton btn_ruf4;
    private javax.swing.JComboBox<String> cmb_rufnamepcktinsrt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_leftweightpcktinsrt;
    private javax.swing.JLabel lbl_pcktnopcktinsrt;
    private javax.swing.JLabel lbl_pcktweightpcktinsrt;
    private javax.swing.JLabel lbl_rufnamepcktinsrt;
    private javax.swing.JLabel lblauto_leftweightpcktinsert;
    private javax.swing.JTable tbl_pcktinsrt;
    private javax.swing.JTextField txt_pcktno;
    private javax.swing.JTextField txt_pcktweightpcktinsrt;
    // End of variables declaration//GEN-END:variables
}
