/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sem2_final;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ReceiveInsert extends javax.swing.JFrame {

    /**
     * Creates new form ReceiveInsert
     */
    Connection con=null;
    PreparedStatement pst = null;
    public ReceiveInsert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_processcode = new javax.swing.JLabel();
        cmb_packet = new javax.swing.JComboBox<>();
        lbl_receiveweight = new javax.swing.JLabel();
        lbl_packetweight = new javax.swing.JLabel();
        cmb_rufname = new javax.swing.JComboBox<>();
        lbl_empname1 = new javax.swing.JLabel();
        text_receive = new javax.swing.JTextField();
        lbl_rufname = new javax.swing.JLabel();
        lbl_packetno = new javax.swing.JLabel();
        lbl_empcode = new javax.swing.JLabel();
        lbl_packet_weight = new javax.swing.JLabel();
        label4 = new java.awt.Label();
        lbl_empname = new javax.swing.JLabel();
        lbl_empcode1 = new javax.swing.JLabel();
        btn_receiveinsert = new javax.swing.JButton();
        lbl_process = new javax.swing.JLabel();
        btn_process = new javax.swing.JButton();
        btn_ruf = new javax.swing.JButton();
        btn_emp = new javax.swing.JButton();
        btn_ruf1 = new javax.swing.JButton();
        btn_ruf3 = new javax.swing.JButton();
        btn_ruf4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DIAMOND MANAGEMENT SYSTEM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Receive Packet");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel2)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setToolTipText("");

        lbl_processcode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_processcode.setText("Process Code:");
        lbl_processcode.setName("lbl_processcodeissueinsert"); // NOI18N

        cmb_packet.setBackground(new java.awt.Color(204, 204, 255));
        cmb_packet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Packet No." }));
        cmb_packet.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmb_packet.setName("cmb_rufnameissueinsert"); // NOI18N

        lbl_receiveweight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_receiveweight.setText("Receive Weight ");
        lbl_receiveweight.setName("lbl_processnameissueinsert"); // NOI18N

        lbl_packetweight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_packetweight.setName("lbl_empcodeissueinsert"); // NOI18N

        cmb_rufname.setBackground(new java.awt.Color(204, 204, 255));
        cmb_rufname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Ruf Name" }));
        cmb_rufname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmb_rufname.setName("cmb_rufnameissueinsert"); // NOI18N
        cmb_rufname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_rufnameActionPerformed(evt);
            }
        });

        lbl_empname1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_empname1.setName("lbl_empcodeissueinsert"); // NOI18N

        text_receive.setBackground(new java.awt.Color(204, 204, 255));
        text_receive.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        text_receive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_receiveActionPerformed(evt);
            }
        });

        lbl_rufname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_rufname.setText("Ruf Name:");
        lbl_rufname.setName("lbl_rufnameissueinsert"); // NOI18N

        lbl_packetno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_packetno.setText("Packet No: ");
        lbl_packetno.setName("lbl_pcktnoissueinsert"); // NOI18N

        lbl_empcode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_empcode.setText("Emp Code: ");
        lbl_empcode.setName("lbl_empcodeissueinsert"); // NOI18N

        lbl_packet_weight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_packet_weight.setText("Weight: ");
        lbl_packet_weight.setName("lbl_weightpcktnoissueinsert"); // NOI18N

        label4.setName("lblauto_processnameissueinsert"); // NOI18N

        lbl_empname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_empname.setText("Emp. Name:");
        lbl_empname.setName("lbl_empnameissueinsert"); // NOI18N

        lbl_empcode1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_empcode1.setName("lbl_empcodeissueinsert"); // NOI18N

        btn_receiveinsert.setBackground(new java.awt.Color(204, 204, 255));
        btn_receiveinsert.setText("Insert");
        btn_receiveinsert.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_receiveinsert.setName("btn_insertissueinsert"); // NOI18N
        btn_receiveinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_receiveinsertActionPerformed(evt);
            }
        });

        lbl_process.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_process.setName("lbl_processcodeissueinsert"); // NOI18N

        btn_process.setText("Process");
        btn_process.setName("btn_addpcktinsert"); // NOI18N
        btn_process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_processActionPerformed(evt);
            }
        });

        btn_ruf.setText("Ruf");
        btn_ruf.setName("btn_addpcktinsert"); // NOI18N
        btn_ruf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rufActionPerformed(evt);
            }
        });

        btn_emp.setText("Emp");
        btn_emp.setName("btn_addpcktinsert"); // NOI18N
        btn_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empActionPerformed(evt);
            }
        });

        btn_ruf1.setText("Issue");
        btn_ruf1.setName("btn_addpcktinsert"); // NOI18N
        btn_ruf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ruf1ActionPerformed(evt);
            }
        });

        btn_ruf3.setText("Packet");
        btn_ruf3.setName("btn_addpcktinsert"); // NOI18N
        btn_ruf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ruf3ActionPerformed(evt);
            }
        });

        btn_ruf4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_ruf4.setText("Logout");
        btn_ruf4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_ruf4.setName("btn_addpcktinsert"); // NOI18N
        btn_ruf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ruf4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_rufname)
                    .addComponent(lbl_packetno)
                    .addComponent(lbl_packet_weight)
                    .addComponent(lbl_empcode)
                    .addComponent(lbl_empname)
                    .addComponent(lbl_processcode)
                    .addComponent(lbl_receiveweight))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_receiveinsert, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ruf4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_process, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_empname1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_empcode1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_packetweight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_ruf1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_emp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmb_rufname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ruf, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(text_receive)
                            .addComponent(cmb_packet, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 257, Short.MAX_VALUE)
                                .addComponent(btn_ruf3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                                .addComponent(btn_process, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(85, 85, 85))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_rufname)
                    .addComponent(cmb_rufname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ruf))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_packetno)
                            .addComponent(cmb_packet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btn_ruf3)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbl_packet_weight))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_packetweight)
                            .addComponent(btn_ruf1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_empcode)
                    .addComponent(lbl_empcode1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_empname)
                    .addComponent(lbl_empname1)
                    .addComponent(btn_emp))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_processcode)
                            .addComponent(lbl_process))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_receiveweight)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_receive, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btn_process)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btn_ruf4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_receiveinsert, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void text_receiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_receiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_receiveActionPerformed

    private void btn_receiveinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_receiveinsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_receiveinsertActionPerformed

    private void btn_processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_processActionPerformed
        // TODO add your handling code here:
        new Process_insert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_processActionPerformed

    private void btn_rufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rufActionPerformed
        // TODO add your handling code here:
        new ruf_insert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_rufActionPerformed

    private void btn_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empActionPerformed
        // TODO add your handling code here:
        new emp_insert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_empActionPerformed

    private void btn_ruf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ruf1ActionPerformed
        // TODO add your handling code here:
        new IssueInsert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ruf1ActionPerformed

    private void btn_ruf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ruf3ActionPerformed
        // TODO add your handling code here:
        new Packet_insert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ruf3ActionPerformed

    private void btn_ruf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ruf4ActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ruf4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
           Class.forName("com.mysql.jdbc.Driver");
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/diamond_packager","root","");
           Statement st = con.createStatement();
           String sql = "SELECT ruf_name FROM ruf r, issue i where i.ruf_id = r.ruf_id";
           ResultSet rs = st.executeQuery(sql);
//           int c=0;
//           cmb_rufname.removeAllItems();
           while(rs.next())
           {        
               String ruf_name = rs.getString("ruf_name");
               cmb_rufname.addItem(ruf_name);               
           }
           
           
//           String ruf_name=(String) cmb_rufname.getSelectedItem();
//           Statement st2 = con.createStatement();
//            String sql2 = "SELECT packet_no FROM packet p, ruf r, employee e, issue i WHERE p.ruf_id = r.ruf_id and r.ruf_id = i.ruf_id and i.emp_code = e.emp_code and i.packet_no = p.packet_no and r.ruf_name= '"+ruf_name+"'";
//            ResultSet rs2 = st2.executeQuery(sql2);
//
//            int itemCount = cmb_packet.getItemCount();
//            while(itemCount > 1){
//                cmb_packet.removeItemAt(itemCount-1);
//                itemCount--;
//            }
//            while(rs2.next())
//            {
//                String p_no = rs2.getString(1);
//                cmb_packet.addItem(p_no);
//            }
           
           
       } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void cmb_rufnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_rufnameActionPerformed
        // TODO add your handling code here:
        try{
            String ruf_name=(String) cmb_rufname.getSelectedItem();
           Statement st2 = con.createStatement();
            String sql2 = "SELECT DISTINCT(p.packet_no) FROM packet p, ruf r, employee e, issue i WHERE r.ruf_id = i.ruf_id and i.emp_code = e.emp_code and i.packet_no = p.packet_no and p.ruf_id = r.ruf_id and r.ruf_name= '"+ruf_name+"'";
            ResultSet rs2 = st2.executeQuery(sql2);

            int itemCount = cmb_packet.getItemCount();
            while(itemCount > 1){
                cmb_packet.removeItemAt(itemCount-1);
                itemCount--;
            }
            while(rs2.next())
            {
                String p_no = rs2.getString(1);
                cmb_packet.addItem(p_no);
            }
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_cmb_rufnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceiveInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceiveInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceiveInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceiveInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceiveInsert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_emp;
    private javax.swing.JButton btn_process;
    private javax.swing.JButton btn_receiveinsert;
    private javax.swing.JButton btn_ruf;
    private javax.swing.JButton btn_ruf1;
    private javax.swing.JButton btn_ruf3;
    private javax.swing.JButton btn_ruf4;
    private javax.swing.JComboBox<String> cmb_packet;
    private javax.swing.JComboBox<String> cmb_rufname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label4;
    private javax.swing.JLabel lbl_empcode;
    private javax.swing.JLabel lbl_empcode1;
    private javax.swing.JLabel lbl_empname;
    private javax.swing.JLabel lbl_empname1;
    private javax.swing.JLabel lbl_packet_weight;
    private javax.swing.JLabel lbl_packetno;
    private javax.swing.JLabel lbl_packetweight;
    private javax.swing.JLabel lbl_process;
    private javax.swing.JLabel lbl_processcode;
    private javax.swing.JLabel lbl_receiveweight;
    private javax.swing.JLabel lbl_rufname;
    private javax.swing.JTextField text_receive;
    // End of variables declaration//GEN-END:variables
}
