/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sem2_final;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ruf_insert extends javax.swing.JFrame {

    /**
     * Creates new form ruf_insert
     */
    Connection con=null;
    PreparedStatement pst = null;
    
    public ruf_insert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_rufinsrt = new javax.swing.JTable();
        btn_rufinsrt = new javax.swing.JButton();
        lbl_rufidrufinsrt = new javax.swing.JLabel();
        lbl_rufnamerufinsrt = new javax.swing.JLabel();
        txt_rufidrufinsrt = new javax.swing.JTextField();
        txt_rufnamerufinsrt = new javax.swing.JTextField();
        lbl_articlerufinsrt = new javax.swing.JLabel();
        txt_articlerufinsrt = new javax.swing.JTextField();
        lbl_weightrufinsrt = new javax.swing.JLabel();
        txt_weightrufinsrt = new javax.swing.JTextField();
        btn_process = new javax.swing.JButton();
        btn_ruf = new javax.swing.JButton();
        btn_emp = new javax.swing.JButton();
        btn_ruf1 = new javax.swing.JButton();
        btn_ruf3 = new javax.swing.JButton();
        btn_ruf4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DIAMOND MANAGEMENT SYSTEM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ruf Insert");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel2)))
                .addGap(0, 199, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        tbl_rufinsrt.setBackground(new java.awt.Color(204, 204, 255));
        tbl_rufinsrt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl_rufinsrt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ruf id", "ruf name", "article", "weight"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_rufinsrt.setName("tbl_ruf"); // NOI18N
        jScrollPane1.setViewportView(tbl_rufinsrt);

        btn_rufinsrt.setBackground(new java.awt.Color(204, 204, 255));
        btn_rufinsrt.setText("Insert");
        btn_rufinsrt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_rufinsrt.setName("btn_rufinsert"); // NOI18N
        btn_rufinsrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rufinsrtActionPerformed(evt);
            }
        });

        lbl_rufidrufinsrt.setText("Ruf id:");

        lbl_rufnamerufinsrt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_rufnamerufinsrt.setText("Ruf Name:");
        lbl_rufnamerufinsrt.setName("lbl_rufname"); // NOI18N

        txt_rufidrufinsrt.setBackground(new java.awt.Color(204, 204, 255));
        txt_rufidrufinsrt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_rufidrufinsrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rufidrufinsrtActionPerformed(evt);
            }
        });

        txt_rufnamerufinsrt.setBackground(new java.awt.Color(204, 204, 255));
        txt_rufnamerufinsrt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_rufnamerufinsrt.setName("txt_rufname"); // NOI18N
        txt_rufnamerufinsrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rufnamerufinsrtActionPerformed(evt);
            }
        });

        lbl_articlerufinsrt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_articlerufinsrt.setText("Article:");
        lbl_articlerufinsrt.setName("lbl_Article"); // NOI18N

        txt_articlerufinsrt.setBackground(new java.awt.Color(204, 204, 255));
        txt_articlerufinsrt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_articlerufinsrt.setName("txt_article"); // NOI18N
        txt_articlerufinsrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_articlerufinsrtActionPerformed(evt);
            }
        });

        lbl_weightrufinsrt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_weightrufinsrt.setText("Weight: ");
        lbl_weightrufinsrt.setName("lbl_weight"); // NOI18N

        txt_weightrufinsrt.setBackground(new java.awt.Color(204, 204, 255));
        txt_weightrufinsrt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_weightrufinsrt.setName("txt_weight"); // NOI18N
        txt_weightrufinsrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_weightrufinsrtActionPerformed(evt);
            }
        });

        btn_process.setText("Process");
        btn_process.setName("btn_addpcktinsert"); // NOI18N
        btn_process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_processActionPerformed(evt);
            }
        });

        btn_ruf.setText("Packet");
        btn_ruf.setName("btn_addpcktinsert"); // NOI18N
        btn_ruf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rufActionPerformed(evt);
            }
        });

        btn_emp.setText("Emp");
        btn_emp.setName("btn_addpcktinsert"); // NOI18N
        btn_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empActionPerformed(evt);
            }
        });

        btn_ruf1.setText("Issue");
        btn_ruf1.setName("btn_addpcktinsert"); // NOI18N
        btn_ruf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ruf1ActionPerformed(evt);
            }
        });

        btn_ruf3.setText("Receive");
        btn_ruf3.setName("btn_addpcktinsert"); // NOI18N
        btn_ruf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ruf3ActionPerformed(evt);
            }
        });

        btn_ruf4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_ruf4.setText("Logout");
        btn_ruf4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_ruf4.setName("btn_addpcktinsert"); // NOI18N
        btn_ruf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ruf4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_rufnamerufinsrt)
                            .addComponent(lbl_rufidrufinsrt))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_rufnamerufinsrt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_rufidrufinsrt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_weightrufinsrt)
                            .addComponent(lbl_articlerufinsrt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_rufinsrt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_articlerufinsrt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_weightrufinsrt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(140, 140, 140)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_ruf, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(btn_ruf1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(btn_ruf4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btn_process, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(btn_ruf3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_rufidrufinsrt)
                            .addComponent(txt_rufidrufinsrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_rufnamerufinsrt)
                            .addComponent(txt_rufnamerufinsrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_articlerufinsrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_articlerufinsrt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_weightrufinsrt)
                            .addComponent(txt_weightrufinsrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(btn_rufinsrt))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ruf3)
                    .addComponent(btn_emp)
                    .addComponent(btn_process))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ruf4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ruf1)
                    .addComponent(btn_ruf))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_rufinsrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rufinsrtActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String query ="INSERT INTO `ruf`(`ruf_id`, `ruf_name`, `article`, `weight`) VALUES (?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/diamond_packager","root","");
            pst=con.prepareStatement(query);
            pst.setString(1,txt_rufidrufinsrt.getText());
            pst.setString(2,txt_rufnamerufinsrt.getText());
            pst.setString(3,txt_articlerufinsrt.getText());
            pst.setString(4,txt_weightrufinsrt.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Ruf DETAILS INSERTED SUCCESSFULLY");

            Statement st = con.createStatement();
            String sql = "SELECT * FROM ruf";
            ResultSet rs = st.executeQuery(sql);
            int c=0;
            while(rs.next())
            {
                String ruf_id = String.valueOf(rs.getInt("ruf_id"));
                String ruf_name = rs.getString("ruf_name");
                String article = rs.getString("article");
                String weight = String.valueOf(rs.getFloat("weight"));

                String tbData[] = {ruf_id, ruf_name, article, weight};
                DefaultTableModel tblModel = (DefaultTableModel)tbl_rufinsrt.getModel();
                tblModel.setRowCount(c++);
                tblModel.addRow(tbData);
            }
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btn_rufinsrtActionPerformed

    private void txt_rufidrufinsrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rufidrufinsrtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rufidrufinsrtActionPerformed

    private void txt_rufnamerufinsrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rufnamerufinsrtActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_txt_rufnamerufinsrtActionPerformed

    private void txt_articlerufinsrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_articlerufinsrtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_articlerufinsrtActionPerformed

    private void txt_weightrufinsrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_weightrufinsrtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_weightrufinsrtActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
                try{
            Class.forName("com.mysql.jdbc.Driver");
//            String query ="INSERT INTO `ruf`(`ruf_id`, `ruf_name`, `article`, `weight`) VALUES (?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/diamond_packager","root","");
           Statement st = con.createStatement();
           String sql = "SELECT * FROM ruf";
           ResultSet rs = st.executeQuery(sql);
           int c=0;
           while(rs.next())
           {
             String ruf_id = String.valueOf(rs.getInt("ruf_id"));
             String ruf_name = rs.getString("ruf_name");
             String article = rs.getString("article");
             String weight = String.valueOf(rs.getFloat("weight"));
               
             String tbData[] = {ruf_id, ruf_name, article, weight};
             DefaultTableModel tblModel = (DefaultTableModel)tbl_rufinsrt.getModel();
               tblModel.setRowCount(c++);
               tblModel.addRow(tbData);
           }
        }
        catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_formWindowOpened

    private void btn_processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_processActionPerformed
        // TODO add your handling code here:
        new Process_insert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_processActionPerformed

    private void btn_rufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rufActionPerformed
        // TODO add your handling code here:
        new Packet_insert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_rufActionPerformed

    private void btn_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empActionPerformed
        // TODO add your handling code here:
        new emp_insert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_empActionPerformed

    private void btn_ruf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ruf1ActionPerformed
        // TODO add your handling code here:
        new IssueInsert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ruf1ActionPerformed

    private void btn_ruf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ruf3ActionPerformed
        // TODO add your handling code here:
        new ReceiveInsert().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ruf3ActionPerformed

    private void btn_ruf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ruf4ActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ruf4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ruf_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ruf_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ruf_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ruf_insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ruf_insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_emp;
    private javax.swing.JButton btn_process;
    private javax.swing.JButton btn_ruf;
    private javax.swing.JButton btn_ruf1;
    private javax.swing.JButton btn_ruf3;
    private javax.swing.JButton btn_ruf4;
    private javax.swing.JButton btn_rufinsrt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_articlerufinsrt;
    private javax.swing.JLabel lbl_rufidrufinsrt;
    private javax.swing.JLabel lbl_rufnamerufinsrt;
    private javax.swing.JLabel lbl_weightrufinsrt;
    private javax.swing.JTable tbl_rufinsrt;
    private javax.swing.JTextField txt_articlerufinsrt;
    private javax.swing.JTextField txt_rufidrufinsrt;
    private javax.swing.JTextField txt_rufnamerufinsrt;
    private javax.swing.JTextField txt_weightrufinsrt;
    // End of variables declaration//GEN-END:variables
}
